### ISSUE TITLE
Typefind +F3

### ISSUE THREAD

**Issue by ZappoB** [canisbos/misc-extensions#1]
Hi there,

I really love you Safari extensions as Typefind - this makes searches on websites easy as on Fx.

But would it be possible to add an find-next-key, as F3 on the normal search? Often the found text is not the searched one. That would improve this tool greatly.

Thanks and best regards.
Zappo

**Comment by canisbos** [comment]
Hi, thanks for the compliment. After finding some string, you can press Tab to find the next occurrence. :)

**Comment by ZappoB** [comment]
Thank you for the quick reply!

I should have read the description on your site more thoughtfully... :/
