### ISSUE TITLE
TypeFind update to exclude hidden elements

### ISSUE THREAD

**Issue by swrobel** [canisbos/misc-extensions#2]
Thanks so much for this extension! I searched for a long time to find the one feature holding me back from using Safari daily. Damn you Firefox for getting me hooked on typeahead find and then getting so bloated & slow!

I updated `injected.js` to use [the logic](https://github.com/tokland/chrome-type-ahead/blob/master/type-ahead.js#L116) from the Chrome [Type-ahead-find extension](https://chrome.google.com/webstore/detail/type-ahead-find/cpecbmjeidppdiampimghndkikcmoadk). A good page to test on is [this one](https://stripe.com/docs/saving-cards) from the Stripe documentation that makes liberal use of `visibility: hidden`. Try searching for `apple`.

```javascript
function findMatchingNodes(string, element, reentrant) {
	if (!reentrant) {
		matchingNodes = [];
		unhighlightPreviousMatch();
	}
	if (element.offsetWidth == 0) return;
	for (var child, i = 0; i < element.childNodes.length; i++) {
		child = element.childNodes[i];
		if (child.nodeType == 3) {
			if (child.nodeValue.toLowerCase().indexOf(string) > -1) {
				var elStyle = window.getComputedStyle(element);
				// Only add to results if element is visible
				if ( elStyle && !(elStyle.visibility === 'hidden' || elStyle.display === 'none')) {
					matchingNodes.push(child);
				}
			}
		} else
		if (child.nodeType == 1) {
			findMatchingNodes(string, child, true);
		}
	}
}
```

**Comment by canisbos** [comment]
Nice. The fact that I didn't know there was a problem shows how much I use this extension (not at all). I will update the code in the distribution. Thanks.

**Comment by canisbos** [comment]
I've pushed the new version of TypeFind. Thanks again for the code.

Although I updated the Update.plist, existing installations of the extension will not find the update since they are still pointing to an Update.plist that no longer exists on Dropbox since Dropbox removed public folders. You can download the updated TypeFind.safariextz file from here, if you wish.
